stages:
  - build
  - package
  - deploy

build:
  stage: build
  image: microsoft/dotnet
  script:
    - dotnet clean
    - dotnet restore
    - dotnet build
    - dotnet publish -o output/
  tags:
    - docker
  artifacts:
    paths: 
      - output/
    expire_in: 1 day

package:
  stage: package
  dependencies:
    - build
  script:
    - docker login -u="nickmramirez+gitlabci" -p="KOPD07R4QEAJYLHR8M2O45SY6U4LK1YGHB7H9SXD6UST1M5IY6ZT6PB2B1M9BJII" quay.io
    - docker build -t quay.io/nickmramirez/ectoplasm:latest .
    - docker push quay.io/nickmramirez/ectoplasm:latest
  tags:
    - shell

deploy:
  stage: deploy
  dependencies:
    - package
  script:
    - az login --service-principal -u $AZ_SERVICE_PRINCIPAL_CLIENT_ID -p $AZ_SERVICE_PRINCIPAL_CLIENT_SECRET --tenant $AZ_TENANT_ID
    - az acs kubernetes get-credentials --resource-group "k8stest_resourcegroup" --name "k8stest_containersvc"
    - kubectl apply -f ./deployment.yml
    - az logout
  tags:
    - shell